name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set tag for dockerhub version
        shell: bash
        run: |
          echo "IMAGE_VERSION=$(date +'%y%m%d-%H%M')" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mfxn3/java-template-tester:${{ env.IMAGE_VERSION }}

